sudo: false

language: cpp

compiler:
  - gcc
  - clang

addons:
  apt:
    sources:
      - llvm-toolchain-precise
      - ubuntu-toolchain-r-test
    packages:
      - clang-3.7
      - gcc-5
      - g++-5
      # Actual dependencies
      - libqt5-dev
      - libglm-dev

install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
  - if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.7" CC="clang-3.7"; fi

script:
  - qmake -r
  - make release
